# Generated by Django 4.2.2 on 2023-06-19 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snacks', '0002_alter_snack_purchaser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snack',
            name='purchaser',
            field=models.TextField(default='Abdullah'),
        ),
    ]
