# Generated by Django 4.2.2 on 2023-06-19 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snacks', '0004_alter_snack_purchaser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snack',
            name='description',
            field=models.TextField(default='blah blah blah'),
        ),
    ]
